FROM python:3.10

RUN apt-get update -y && \
    apt-get -y --no-install-recommends install \
    software-properties-common openjdk-17-jdk

WORKDIR /app
RUN chmod -R 777 /app
COPY *.py .
COPY requirements.txt .

RUN pip install -r requirements.txt
ENTRYPOINT ["python3", "./analytics.py"]
